# Configuration generale des scans
scan:
  timeout: 300
  threads: 10
  user_agent: "SecurityAuditTool/1.0"
  modules:
    - "network"
    - "http"

# Configuration du scanner reseau
network:
  ports:
    - 21
    - 22
    - 23
    - 25
    - 53
    - 80
    - 110
    - 111
    - 135
    - 139
    - 143
    - 443
    - 993
    - 995
    - 1723
    - 3306
    - 3389
    - 5432
    - 5900
    - 8080
    - 8443
    - 9200
    - 9300
  top_ports: 1000
  tcp_timeout: 5
  udp_timeout: 5
  max_threads: 50
  os_detect: true
  banner_grab: true
  service_scan: true

# Configuration du scanner HTTP
http:
  follow_redirects: true
  max_redirects: 5
  timeout: 30
  user_agent: "SecurityAuditTool/1.0"
  headers:
    - "Strict-Transport-Security"
    - "Content-Security-Policy"
    - "X-Frame-Options"
    - "X-Content-Type-Options"
    - "X-XSS-Protection"
    - "Referrer-Policy"
    - "Permissions-Policy"
    - "Expect-CT"
  cookies:
    - "Secure"
    - "HttpOnly"
    - "SameSite"
  ssl_check: true
  check_redirects: true

# Configuration du serveur web
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120

# Configuration des logs
log_level: "info"

# Configuration des rapports
reports:
  default_format: "json"
  include_raw_data: false
  max_findings: 1000

# Configuration des notifications
notifications:
  enabled: false
  webhook_url: ""

# Configuration avancee
advanced:
  max_scan_time: 3600
  max_concurrent_scans: 5
  cache_enabled: true
  cache_ttl: 3600